site:
  author: Arawn-Park!!!
  description: todoapp workshop 1 day!!!
  features:
    auth: true
    onlineUsersCounter: true

logging.level:
  todoapp: DEBUG
  org.springframework.boot: INFO
  org.springframework.web: DEBUG